### ISSUE TITLE
[Bug]: 远程服务无法正常上传

### ISSUE THREAD

**Issue by somnifex** [Kuingsmile/vs-PicList#1]
### 系统信息 | System Information

Windows

### 问题重现 | Bug reproduce

我通过服务器运行piclist并试图在另外的电脑上传图片，我发现vscode插件上传剪贴板时因远程剪贴板内无本地剪贴板中的图片导致上传失败。在obsidian的image auto upload插件中有一个远程服务器模式能够解决这个问题，可供参考
![屏幕截图 2023-12-06 141529](https://github.com/Kuingsmile/vs-PicList/assets/98788152/b90fe73c-f1f7-4ef3-83b1-0e50ef24e4ea)

**Comment by Kuingsmile** [comment]
obsidian的image auto upload插件的远程模式是我和插件作者配合更新的,然后那边更新完忘了vs插件的了，我去修改下vs插件部分的代码

**Comment by somnifex** [comment]
> obsidian的image auto upload插件的远程模式是我和插件作者配合更新的,然后那边更新完忘了vs插件的了，我去修改下vs插件部分的代码

哈哈哈哈 ，感谢

**Comment by Kuingsmile** [comment]
support remote server mode in v1.2.0
