### ISSUE TITLE
[Bug]: MacOS | 在VSCODE粘贴复制的图片后不会自动上传到远程

### ISSUE THREAD

**Issue by daynoti** [Kuingsmile/vs-PicList#2]
### 系统信息 | System Information

Mac

## VSCODE 直接粘贴图片进入markdown编辑器，会直接变成本地图片，不会上传到远程
<img width="566" alt="image" src="https://github.com/Kuingsmile/vs-PicList/assets/124574438/dda06c31-d3e3-4e8f-b1bc-1d3359101932">
<img width="815" alt="image" src="https://github.com/Kuingsmile/vs-PicList/assets/124574438/e07a2ad2-2f80-4435-9430-df6c9e2f413f">
<img width="815" alt="image" src="https://github.com/Kuingsmile/vs-PicList/assets/124574438/ff2dd31a-aa36-4368-9a07-e0cb535c2378">
<img width="1200" alt="image" src="https://github.com/Kuingsmile/vs-PicList/assets/124574438/440bed34-faf3-46c4-b4c8-58476c05d0a8">

# Typora上传没有这样的问题
<img width="932" alt="image" src="https://github.com/Kuingsmile/vs-PicList/assets/124574438/5d05ccb1-4b4b-4f88-a157-bb05c7331a0f">

**Comment by daynoti** [comment]
不知道是什么原因导致的，请求解答，谢谢大佬

**Comment by Kuingsmile** [comment]
和typora不一样 vscode里需要通过拖拽或者快捷键上传，默认的快捷方式是ctrl+alt+U上传剪贴板图片
![image](https://github.com/Kuingsmile/vs-PicList/assets/96409857/5fee995b-2a4c-4d8a-85ac-330137900b4e)

**Comment by daynoti** [comment]
好哒，明白啦，多谢解答
