### ISSUE TITLE
[Feature]: 批量转存 markdown 文件中的图片

### ISSUE THREAD

**Issue by nexmoe** [Kuingsmile/vs-PicList#3]
### 系统信息 | System Information

Windows

### 功能请求 | Feature request

右键，然后解析 markdown 中的图片并转存

**Comment by Kuingsmile** [comment]
https://github.com/PicGo/picgo-plugin-pic-migrater

建议使用该插件

**Comment by nexmoe** [comment]
也许可以考虑在 vscode 插件里集成一下这个插件的能力？

**Comment by Kuingsmile** [comment]
可以考虑
