### ISSUE TITLE
[Feature]: 我如果需要在粘贴图片后自动上传,上传完成后自动替换之前的路径, 需要怎么做

### ISSUE THREAD

**Issue by Pupper0601** [Kuingsmile/vs-PicList#4]
### 系统信息 | System Information

Mac

### 功能请求 | Feature request

![image](https://github.com/user-attachments/assets/3ae9de77-4460-43d3-ba65-275c26ae573a)
目前粘贴完成后是上面的效果, 我需要在粘贴图片后自动出现下面的结果, 不需要使用快捷键或者其他方式来触发上传.

**Comment by Kuingsmile** [comment]
我看下

**Comment by Kuingsmile** [comment]
图片上面的行为是vscode的内置机制实现的，如果想实现下面的效果，需要使用vscode的proposed api，但一旦使用就无法公开上架。
