### ISSUE TITLE
[Feature]: 能否增加监听剪切板上传的功能

### ISSUE THREAD

**Issue by Pupper0601** [Kuingsmile/vs-PicList#5]
### 系统信息 | System Information

Mac

### 功能请求 | Feature request

我的想法是, 当我打开这个选项时, 就会自动监听我的剪切板, 执行上传任务

piclist 支持监听剪切板, 但是打开后在我不使用 vscode 时依然会上传, 需要手动去关闭

**Comment by Kuingsmile** [comment]
https://github.com/Kuingsmile/vs-PicList/issues/4
参考这个issue ，这个功能的实现需要用到还在proposed阶段的api，使用后不能发布到市场
