### ISSUE TITLE
[Bug]: macOS|Uploading images on Drag-and-Drop失效

### ISSUE THREAD

**Issue by EastonVoyager** [Kuingsmile/vs-PicList#6]
### 系统信息 | System Information

Mac

### 问题重现 | Bug reproduce

<img width="1531" alt="image" src="https://github.com/user-attachments/assets/2d89e9b1-7e98-4f8a-9bad-2f898bc3500e">
拖入上传失效，不按shift是打开图片，按shift后插入的是本地链接
<img width="1246" alt="image" src="https://github.com/user-attachments/assets/46f052db-a982-4ecc-8d3e-306d16bd2658">

setting:
<img width="1095" alt="image" src="https://github.com/user-attachments/assets/2d186c94-b047-4f69-b239-2814efe9b92e">

Mac信息：
- processor: 2 GHz Quad-Core Intel Core i5
- macOS: 14.4.1 (23E224)

vscode: June 2024 (version 1.91)

重新打开vscode以及重启都试过了，帮忙看一下是不是哪里没设置，谢谢！

**Comment by Kuingsmile** [comment]
fixed
